// Generated by uniffi-bindgen-react-native
#include "iroh-ffi.h"
#include "generated/iroh_ffi.hpp"

namespace irohffi {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeIrohFfi::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}