// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "iroh-ffi.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "IrohFfiSpec.h"

@interface IrohFfi : NSObject <NativeIrohFfiSpec>
#else
#import <React/RCTBridgeModule.h>

@interface IrohFfi : NSObject <RCTBridgeModule>
#endif

@end