// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "iroh-spike.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "IrohSpikeSpec.h"

@interface IrohSpike : NSObject <NativeIrohSpikeSpec>
#else
#import <React/RCTBridgeModule.h>

@interface IrohSpike : NSObject <RCTBridgeModule>
#endif

@end